-- MySQL Script generated by MySQL Workbench
-- Sat Jun 17 18:23:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Ocupacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ocupacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ocupacion` (
  `codigoOcupacion` INT NOT NULL,
  `nombre` VARCHAR(15) NOT NULL,
  `sueldo` INT NOT NULL,
  PRIMARY KEY (`codigoOcupacion`),
  UNIQUE INDEX `codigoOcupación_UNIQUE` (`codigoOcupacion` ASC))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Poblar Table `mydb`.`Ocupacion`
-- -----------------------------------------------------
INSERT INTO Ocupacion(codigoOcupacion, nombre, sueldo)
    Values
    ('124' , 'Gerente General' , '5000000' ),
    ('125' , 'Ingeniería Civil Informática' , '650000' ),
    ('126' , 'Ingeniería Civil en Ciencia de Datos' , '300000' ),
    ('127' , 'Ingeniería Civil en Telecomunicaciones' , '400000' ),
    ('128' , 'Ingeniería Civil Electrónica' , '3500000' );

-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Departamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `codigoUnico` INT NOT NULL,
  `fechaIniGerente` DATETIME NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `esOperativo` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`codigoUnico`),
  UNIQUE INDEX `codigoUnicoOperativo_UNIQUE` (`codigoUnico` ASC))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Poblar Table `mydb`.`Departamento`
-- -----------------------------------------------------
INSERT INTO Departamento(codigoUnico, nombre, fechaIniGerente, esOperativo)
    Values
    ('024' , 'Rojo' , '2014-01-20 13:00:55' , '0'),
    ('025' , 'Azul' , '2015-01-20 13:00:55' , '1' ),
    ('026' , 'Negro' , '2016-01-20 13:00:55' , '0' ),
    ('027' , 'Blanco' , '2017-01-20 13:00:55' , '1' ),
    ('028' , 'Naranjo' , '2018-01-20 13:00:55' , '1');

-- -----------------------------------------------------
-- Table `mydb`.`Personal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Personal` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Personal` (
  `idPersonal` VARCHAR(20) NOT NULL,
  `Personal_idPersonal` VARCHAR(20) NOT NULL,
  `Ocupacion_codigoOcupacion` INT NOT NULL,
  `Departamento_codigoUnico` INT NOT NULL,
  `nombres` VARCHAR(15) NOT NULL,
  `primerApellido` VARCHAR(15) NOT NULL,
  `segundoApellido` VARCHAR(15) NOT NULL,
  `sexo` ENUM('0', '1', '2') NOT NULL DEFAULT '0',
  `direccion` VARCHAR(200) NOT NULL,
  `fechaNacPersonal` DATETIME NOT NULL,
  `asignacionesExtras` INT NOT NULL,
  PRIMARY KEY (`idPersonal`),
  UNIQUE INDEX `idPersonal_UNIQUE` (`idPersonal` ASC),
  INDEX `fk_Personal_Ocupacion1_idx` (`Ocupacion_codigoOcupacion` ASC),
  INDEX `fk_Personal_Personal1_idx` (`Personal_idPersonal` ASC),
  INDEX `fk_Personal_Departamento1_idx` (`Departamento_codigoUnico` ASC),
  CONSTRAINT `fk_Personal_Ocupacion1`
    FOREIGN KEY (`Ocupacion_codigoOcupacion`)
    REFERENCES `mydb`.`Ocupacion` (`codigoOcupacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personal_Personal1`
    FOREIGN KEY (`Personal_idPersonal`)
    REFERENCES `mydb`.`Personal` (`idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personal_Departamento1`
    FOREIGN KEY (`Departamento_codigoUnico`)
    REFERENCES `mydb`.`Departamento` (`codigoUnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carga_Familiar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Carga_Familiar` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Carga_Familiar` (
  `idCarga_Familiar` VARCHAR(20) NOT NULL,
  `Personal_idPersonal` VARCHAR(20) NOT NULL,
  `parentesco` ENUM('1', '2', '3') NOT NULL DEFAULT '3',
  `sexo` ENUM('0', '1', '2') NOT NULL DEFAULT '0',
  `fechaNac` DATETIME NOT NULL,
  `nombreCompleto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCarga_Familiar`),
  INDEX `fk_Carga_Familiar_Personal1_idx` (`Personal_idPersonal` ASC),
  UNIQUE INDEX `idCarga_Familiar_UNIQUE` (`idCarga_Familiar` ASC),
  CONSTRAINT `fk_Carga_Familiar_Personal1`
    FOREIGN KEY (`Personal_idPersonal`)
    REFERENCES `mydb`.`Personal` (`idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Proyecto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Proyecto` (
  `NumeroUnico` INT NOT NULL,
  `Departamento_codigoUnico` INT NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NumeroUnico`),
  UNIQUE INDEX `NumeroUnico_UNIQUE` (`NumeroUnico` ASC),
  INDEX `fk_Proyecto_Departamento1_idx` (`Departamento_codigoUnico` ASC),
  CONSTRAINT `fk_Proyecto_Departamento1`
    FOREIGN KEY (`Departamento_codigoUnico`)
    REFERENCES `mydb`.`Departamento` (`codigoUnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personal_Proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Personal_Proyecto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Personal_Proyecto` (
  `Proyecto_NumeroUnico` INT NOT NULL,
  `Personal_idPersonal` VARCHAR(20) NOT NULL,
  `horas_Mensuales` FLOAT NULL,
  PRIMARY KEY (`Proyecto_NumeroUnico`, `Personal_idPersonal`),
  INDEX `fk_Personal_Proyecto_Personal1_idx` (`Personal_idPersonal` ASC),
  CONSTRAINT `fk_Personal_Proyecto_Proyecto1`
    FOREIGN KEY (`Proyecto_NumeroUnico`)
    REFERENCES `mydb`.`Proyecto` (`NumeroUnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personal_Proyecto_Personal1`
    FOREIGN KEY (`Personal_idPersonal`)
    REFERENCES `mydb`.`Personal` (`idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Oficina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Oficina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Oficina` (
  `idOficina` INT NOT NULL,
  `Departamento_codigoUnico` INT NOT NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`idOficina`),
  UNIQUE INDEX `idOficinas_UNIQUE` (`idOficina` ASC),
  INDEX `fk_Oficina_Departamento1_idx` (`Departamento_codigoUnico` ASC),
  CONSTRAINT `fk_Oficina_Departamento1`
    FOREIGN KEY (`Departamento_codigoUnico`)
    REFERENCES `mydb`.`Departamento` (`codigoUnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
